swagger: '2.0'
info:
  version: 1.0.0
  title: InventoryAPI
  description: Field Logistics Platform - Inventory Management Service.
  contact:
    name: FLM Team
    email: flmsupport@slb.com
  license:
    name: Schlumberger proprietary
    url: 'http://www.slb.com'
tags:
  - name: Inventory
    description: Operations on Good Issues, Good receipt
externalDocs:
  description: "You can find more details on the url"
  url: "https://flm.slb.com"
host: flm.slb.com
basePath: /market-to-cash/inventory123
schemes:
  - https
security:
  - ApiKeyAuth: []
paths:
  /inventory:
    post:
      tags:
        - Inventory
      summary: Method to submit inventory movement
      operationId: Inventory
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - application/json
      parameters:
        - name: operation
          in: path
          description: 'Submit Good issue, Submit Good receipt, reverse good receipt, reverse good issue, submit consumption, reverse consumption'
          required: true
          type: string
          default: "SubmitGR"
        - name: data
          in: body
          description: ''
          required: false
          schema:
            type: array
            items:
              $ref: '#/definitions/Inventory'
            uniqueItems: false
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/InventoryResponse'
        '308':
          description: The resource requested has been superseded.
          schema:
              $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Operation
        '404':
          description: Resource not found
securityDefinitions:
  ApiKeyAuth:
    type: "apiKey"
    in: "header"
    name: "x-apikey"
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
definitions:
  Inventory:
    type: array
    properties:
      type:
        type: string
      attributes:
        $ref: >-
          #/definitions/InventoryAttributes
      CreatedDate:
        format: date-time
        type: string
      CreatedBy:
        type: string
      LastModifiedDate:
        format: date-time
        type: string
      LastModifiedBy:
        type: string
      Id:
        type: string
  InventoryAttributes:
    type: object
    properties:
      shipmentId:
        description: 'Shipment Identifier'
        type: string
      shippingId:
        description: 'Shipping Request Identifier'
        type: string
      Comments:
        type: string
      TimeZoneStandardName:
        type: string
      BOLNumber:
        type: string
      JobId:
        type: string
      PONumber:
        type: string
      SAPProjectNumber:
        type: string
      Materials:
        uniqueItems: false
        type: array
        items:
          $ref: >-
            #/definitions/Material
  ShipmentSource:
    type: object
    properties:
      Source:
        type: string
      SourceDescription:
        type: string
      SourceStorageLocation:
        type: string
      SourceStorageLocationDescription:
        type: string
      SourceAltShip:
        type: string
      SourceAltShipDescription:
        type: string
      SourceShippingPoint:
        type: string
  ShipmentDestination:
    type: object
    properties:
      Destination:
        type: string
      DestinationDescription:
        type: string
      DestinationStroageLocation:
        type: string
      DestinationStorageLocationDescription:
        type: string
      DestinationAltShip:
        type: string
      DestinationAltShipDescription:
        type: string
      DestinationShippingPoint:
        type: string
  InventoryRelationships:
    type: object
    properties:
      data:
        uniqueItems: false
        type: array
        items:
          $ref: >-
            #/definitions/ShipmentsRelationshipsData
  ShipmentCostInfo:
    type: object
    properties:
      CostType:
        type: string
      Amount:
        type: string
      CurrencyCode:
        type: string
  Material:
    type: object
    properties:
      MaterialId:
        type: string
      MaterialNumber:
        type: string
      MaterialName:
        type: string
      MaterialType:
        type: string
      Uom:
        type: string
      Quantity:
        format: double
        type: number
      ValuationType:
        type: string
      ValuationValue:
        type: string
      ValuationSerialValue:
        type: string
      ValuationSplitValue:
        type: string
      Batch:
        type: string
      DeliveryDate:
        format: date-time
        type: string
  TransferPosting:
    type: object
    properties:
      MatDocNo:
        type: string
      MatDocNoSplit:
        type: string
      MatDocNoUnrest:
        type: string
      MatDocYear:
        type: string
      MatDocYearSplit:
        type: string
      MatDocYearUnrest:
        type: string
      AllocMatDocNo:
        type: string
      AllocMatDocYear:
        type: string
      DeallocMatDocNo:
        type: string
      DeallocMatDocYear:
        type: string
      RevDeallocMatDocNo:
        type: string
      RevDeallocMatDocYear:
        type: string
      RevMatDocNo:
        type: string
      RevMatDocNoSplit:
        type: string
      RevMatDocNoUnrest:
        type: string
      RevMatDocYear:
        type: string
      RevMatDocYearSplit:
        type: string
      RevMatDocYearUnrest:
        type: string
      RevMatDocOneStep:
        type: string
      RevMatDocOneStepYear:
        type: string
      MatDocDeAllocation:
        type: string
      MatDocDeAllocYear:
        type: string
      MaterialSlip:
        type: string
      DocHdrTxt:
        type: string
      MatDocOneStep:
        type: string
      MatDocOneStepYear:
        type: string
      DelvNum:
        type: string
      MatDoc:
        type: string
      DivertMatDoc:
        type: string
      PrjStkMatDoc:
        type: string
      PkgtoBulkMatDoc:
        type: string
  ShipmentsRelationshipsData:
    type: object
    properties:
      WellId:
        type: string
      WellName:
        type: string
      IsExpressRequest:
        type: boolean
      ExternalId:
        type: string
      DestinationJobId:
        type: string
      DestinationWellId:
        type: string
      DestinationWellName:
        type: string
      DestinationJobSAPProjectNumber:
        type: string
      ShipmentId:
        type: string
      ShippingId:
        type: string
      MobilizationId:
        type: string
      TransportId:
        type: string
      HandlingUnitId:
        type: string
  InventoryResponse:
    type: object
    properties:
      id:
        type: string
      Type:
        type: string
      Attributes:
        $ref: >-
          #/definitions/InventoryResponseAttributes
      Relationships:
        $ref: >-
          #/definitions/InventoryResponseRelationships
  InventoryResponseAttributes:
    type: object
    properties:
      LogisticsDetails:
        type: string
      SourceShipment:
        type: string
      IsSapDeployed:
        type: boolean
      IsMobType:
        type: boolean
      SourceType:
        type: string
      OpsLocationCode:
        type: string
      Customer:
        type: string
      Rig:
        type: string
      InternalTransferPostingNo:
        type: string
      TransferPosting:
        $ref: '#/definitions/TransferPosting'
      TransferPostingAudit:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/TransferPosting'
      Status:
        type: string
      Source:
        type: string
      ShipmentSource:
        $ref: '#/definitions/ShipmentSource'
      ShipmentDestination:
        $ref: >-
          #/definitions/ShipmentDestination
      Materials:
        uniqueItems: false
        type: array
        items:
          $ref: >-
            #/definitions/Material
      CostInfo:
        uniqueItems: false
        type: array
        items:
          $ref: >-
            #/definitions/ShipmentCostInfo
      TimeZoneStandardName:
        type: string
      BOLNumber:
        type: string
  InventoryResponseRelationships:
    type: object
    properties:
      data:
        uniqueItems: false
        type: array
        items:
          $ref: >-
            #/definitions/InventoryRelationships
  ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string

