swagger: '2.0'
info:
  version: '1.0'
  title: Domain MetaData
  description: Schlumberger API for MDM Domain MetaData.
  contact:
    name: MDM Team
    email: itmasterdatamanagement@slb001.onmicrosoft.com
  license:
    name: Schlumberger proprietary
externalDocs:
  description: "Find out more on the SLB WIKI"
  url: "https://wiki.slb.com/display/ea/Developer%27s+Guide+to+Self-Service"
host: apigateway.evq.it.slb.com
basePath: /central-it
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
#Authentication    
security:
  - APIKeyHeader: []  

tags:
  - name: metadata
    description: This API represents Schlumberger Meta Data for Domains

paths:
  /metadata/{domain}:
    get:
      tags:
        - metadata
      summary: Get Meta Data for a Domain
      description: |
        This operation returns a Domain Meta Data by passing the Domain Name
      operationId: getDomainMetaData
      deprecated: false
      produces:
      - application/json
      parameters:
        - $ref: '#/parameters/domainPath'
      responses:
        '200': 
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/unauthorized'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFound'
        '405':
          $ref: '#/responses/notAllowed'
        '406':
          $ref: '#/responses/notAcceptable'
        '429':
          $ref: '#/responses/requestLimitExceeded'
        '500':
          $ref: '#/responses/serverError'
        '503':
          $ref: '#/responses/serviceUnavailable'

securityDefinitions:
  APIKeyHeader:
    type: "apiKey"
    name: "x-apikey"
    in: "header"

parameters:
  domainPath:
    name: domain
    in: path
    description: Domain Name for which metaData needs to be returned
    required: true
    type: string
    default: wellbore
    enum: [wellbore,cust,material,rig,slorg_bt,slorg_bv]
#TODO: flesh out error responses
responses:
  success:
    description: Success
    schema:
      $ref: '#/definitions/Domain'
  badRequest:
    description: Bad Request
    schema:
      $ref: '#/definitions/ApiResponse'
  unauthorized:
    description: Unauthorized
  forbidden:
    description: Forbidden
  notAllowed:
    description: Not Allowed
  notAcceptable: 
    description: Not Acceptable
  notFound:
    description: Not Found
    schema:
      $ref: '#/definitions/ApiResponse'
  requestLimitExceeded:
    description: Request Limit Exceeded
  serverError:
    description: Server Error
    schema:
      $ref: '#/definitions/ApiResponse'
  serviceUnavailable:
    description: Service Unavailable

definitions:
  Domain:
    type: object
    required:
      - domain
    properties:
      count:
        type: string
        pattern: '^\d{1,9}$'
        description: Total Count of Domain Entities.
        example: '43456785'
      lastUpdateDate:
        type: string
        description: The last date/time domain Data has changed
        example: '2019-11-18T11:52:10Z'
        format: date-time
    xml:
      name: domain
  ApiResponse:
    type: object
    properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
