swagger: "2.0"
info:
    version: "1.0.0"
    title: First Mile Digitalization API
consumes:
    - "application/json"
produces:
    - "application/json"
schemes:
    - "https"
host: evd.apigateway.slb.com
basePath: /proppants/
