swagger: "2.0"
info:
  description: "\n# What does this API do?\nThis API will allow you to perform a search on all of the accounts payable invoices at Schluberger and retrieve detailed information about an invoice with invoice number and additional filters. \n\n# \n"
  version: 1.0.0
  title: AP Invoices API
  contact:
    name: Hardik Dave
    email: hdave@slb.com
  license:
    name: '(c) Copyright Schlumberger, unpublished work, created 02/06/2020'
    url: https://www.slb.com
host: evd.apigateway.slb.com
basePath: /demand-to-deliver
externalDocs:
    description: 'Find out more on the SLB Wiki'
    url: 'https://wiki.slb.com'
tags:
- name: AP Invoices
  description: Retrieve AP Invoices across systems
schemes:
- https
consumes:
- application/json
produces:
- application/json
security:
- APIKeyHeader: []
- OAuth2: []
paths:
  /invoices:
    get:
      tags:
      - AP Invoices
      summary: AP Invoices for Schlumberger Corporation.
      description: "This operation allows you to search for an AP Invoice based on the following filters\n\n  - If you do not add any query string parameters(search filters), this operation will will results all the invoices status of all systems.\n  - Use the <b>page</b> parameter to indicate the page you would like returned\n  - Use <b>count</b> to indicate the number of invoices to return in each response. \n  - You can use ?<b>vendorName</b>=\"RICKMAN TRANSPORT LLC\" to limit your search to only invoices for a specific vendor\n  - You can use ?<b>urn</b>='241048223' to search by URN\n  - You can do date range search by using from and end date filters e.g ?<b>invoiceDateFrom</b> >=\"2019-10-01\" and <b>invoiceDateEnd</b> <=\"2019-10-30\"\n   - For Date Search which is for the same day you can specify same value in From and End Date filters e.g ?<b>invoiceDateFrom</b> >=\"2019-10-01\" and <b>invoiceDateEnd</b> <=\"2019-10-01\"\n  - When only From Date is specified for the Date Filter, systems searchs for records all the records from the specified date to last record available in the system which matches the criteria.\"\n - You can use any of these query sting variables in combination to do your search. \n  - Use the search parameter to do a text match search on the Vendor Name. \n  \n\nThe maximum number of items that will be returned in a page will be 1000.\n  \n"
      operationId: apinvoices
      produces:
        - application/json
      parameters:
      - name: Authorization
        in: header
        description: This is the value of your OAuth2 Bearer token. The value should be structured like "Bearer" + " " + OAuth Token
        required: false
        type: string
      - name: Accept
        in: header
        description: The requested format for the return payload
        required: true
        type: string
        enum:
        - application/json
      - name: x-slb-invoicenumber
        in: header
        description: Enter a value if you would like to track your transactions through the Apigee monitoring tool (Apigee BAM)
        required: false
        type: string
      - name: x-slb-vendorname
        in: header
        description: Enter a value if you would like to track your transactions through the Apigee monitoring tool (Apigee BAM)
        required: false
        type: string
      - name: x-slb-companycode
        in: header
        description: Enter a value if you would like to track your transactions through the Apigee monitoring tool (Apigee BAM)
        required: false
        type: string
      - name: system
        in: query
        description: ERP System or Operations System where transactions are performed. When System is used is selection parameter for requesting invoices, always use invoice status and other combination to reduce the volume of data.
        required: false
        type: string
        enum:
        - SAPITT
        - Lawson
        - OracleMI
        - Accenture-DFM
      - name: urn
        in: query
        description: URN is barcode used to Scanning and MySupplierPortal
        required: false
        type: string
      - name: invoice-number
        in: query
        description: Number which uniquely identifies an invoice document, this may be array of mutiple unique invoice numbers
        type: array
        collectionFormat: multi
        uniqueItems: true
        items:
          type: string
      - name: vendor-id
        in: query
        description: Account Number of Vendor or Creditor. Specifies an alphanumeric key that uniquely identifies the vendor in the system
        required: false
        type: string
      - name: vendor-name
        in: query
        description: Name of the vendor (external supplier) or supplying plant from which the materials are to be procured.
        required: false
        type: string
      - name: company-code
        in: query
        description: The company code is an organizational unit within financial accounting that represents a legal entity
        required: false
        type: string
      - name: geo-market
        in: query
        description: A geographical area where Schlumberger does business. It may consist of a country, a part of a country, or multiple countries, forming a region where business goals and business practices are very similar
        required: false
        type: string
      - name: invoice-date-from
        in: query
        description: Specifies the date on which the invoice was initiated by vendor (external supplier). Diplayed on Vendor invoice document
        required: false
        type: string
        format: date
        x-chance: date
      - name: invoice-date-end
        in: query
        description: Specifies the date on which the invoice was initiated by vendor (external supplier). Diplayed on Vendor invoice document
        required: false
        type: string
        format: date
        x-chance: date
      - name: invoice-receive-date-from
        in: query
        description: Specifies the date on which the invoice was received.
        required: false
        type: string
        format: date
        x-chance: date
      - name: invoice-receive-date-end
        in: query
        description: Specifies the date on which the invoice was received.
        required: false
        type: string
        format: date
        x-chance: date
      - name: count
        in: query
        description: the number of records to return in a single page of search results
        required: false
        type: integer
        default: 1000
        format: int32
      - name: page
        in: query
        description: the specific page number.
        required: false
        type: integer
        default: 1
        format: int32
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/APInvoices'
        401:
          description: Unauthorized Request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Unauthorized Request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Requested Item Not Found
          schema:
            $ref: '#/definitions/Error'
        429:
          description: Request Limit Exceeded
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        503:
          description: Service Unavailable
          schema:
            $ref: '#/definitions/Error'
  /invoices/{invoice-number}:
    get:
      tags:
      - AP Invoices
      summary: Get an invoice by  Invoice Number
      description: This api is used to get the invoice status information by passing <b>invoice-number</b> and if you want to search in a specific system you can pass <b>system</b> as optional query param.
      operationId: apinvoicebyID
      produces:
        - application/json
      parameters:
      - name: Authorization
        in: header
        description: This is the value of your OAuth2 Bearer token. The value should be structured like "Bearer" + " " + OAuth Token
        required: false
        type: string
      - name: Accept
        in: header
        description: The requested format for the return payload
        required: true
        type: string
        enum:
        - application/json
      - name: x-slb-invoicenumber
        in: header
        description: Enter a value if you would like to track your transactions through the Apigee monitoring tool (Apigee BAM)
        required: false
        type: string
      - name: invoice-number
        in: path
        description: Number which uniquely identifies an invoice document.
        required: true
        type: string
      - name: system
        in: query
        description: ERP System or Operations System where transactions are performed. When System is used is selection parameter for requesting invoices, always use invoice status and other combination to reduce the volume of data.
        required: false
        type: string
        enum:
        - SAPITT
        - Lawson
        - OracleMI
        - Accenture-DFM

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/APInvoiceList'
        401:
          description: Unauthorized Request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Unauthorized Request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Requested Item Not Found
          schema:
            $ref: '#/definitions/Error'
        429:
          description: Request Limit Exceeded
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        503:
          description: Service Unavailable
          schema:
            $ref: '#/definitions/Error'
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    name: x-apikey
    in: header
  OAuth2:
    type: oauth2
    tokenUrl: https://{host}/oauth2/token
    flow: application
definitions:
  APInvoices:
    allOf:
    - $ref: '#/definitions/Paging'
    - type: object
      properties:
        data:
          $ref: '#/definitions/APInvoice'
  APInvoiceList:
      type: array
      items:
          $ref: '#/definitions/APInvoice'
          
  Error:
    type: object
    properties:
      title:
        type: string
        example: User First Name cannot be empty
        description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
      detail:
        type: string
        example: Enter a value in the First Name field. If you do not know the first name then enter a space. The First Name field cannot be submitted with a null.
        description: A human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized.
  Paging:
    type: object
    properties:
      next:
        type: string
        example: https://{host}/demand-to-deliver/invoices?page=3&count=1000
        description: Link to the next page
      prev:
        type: string
        example: https://{host}/demand-to-deliver/invoices?page=1&count=1000
        description: Link to the previous page. Only if the current page is greater than 1.
      page:
        type: integer
        format: int32
        example: 1
        description: current page in the pages collection
      itemsPerPage:
        type: integer
        format: int32
        example: 1000
        description: number of records on a page
      resultsCount:
        type: integer
        format: int32
        example: 31635
        description: total number of results returned for search
      totalPages:
        type: integer
        format: int32
        example: 32
        description: total number of pages in the collection
      nextPage:
        type: integer
        format: int32
        example: 3
        description: next page
      prevPage:
        type: integer
        format: int32
        example: 2
        description: previous page
  APInvoice:
    type: object
    properties:
      invoiceStatus:
        type: string
        example: UNPAID-READY FOR PAYMENT
        description: Processing Status of the Invoice Document (Pending, Paid, rejected etc.)
      system:
        type: string
        example: Accenture - DFM
        description: ERP System or Operations System where transactions are performed
      invoiceNumber:
        type: string
        example: "5106036407"
        description: Number which uniquely identifies an invoice document.
      urn:
        type: string
        example: "241048223"
        description: 'URN is barcode used to Scanning and MySupplierPortal '
      usdAmount:
        type: number
        format: double
        example: 115000.0
        description: Invoice Line Item amount in group currency for Schlumberger (USD).
      transactionAmount:
        type: number
        format: double
        example: 115000.0
        description: Invoice Line Item amount in the currency in which a document is posted.
      documentStatus:
        type: string
        example: POSTED
        description: 'Document Status of the Invoice '
      currency:
        type: string
        example: USD
        description: The unit in which the Invoice amount is expressed. The Invoice amount must have a currency (for example, US dollars)
      vendorID:
        type: string
        example: "1000009131"
        description: Account Number of Vendor or Creditor. Specifies an alphanumeric key that uniquely identifies the vendor in the system
      vendorName:
        type: string
        example: RICKMAN TRANSPORT LLC
        description: Name of the vendor (external supplier) or supplying plant from which the materials are to be procured.
      geoMarket:
        type: string
        example: SCA
        description: 'A geographical area where Schlumberger does business. It may consist of a country, a part of a country, or multiple countries, forming a region where business goals and business practices are very similar. '
      area:
        type: string
        example: MEA
        description: A region of the world where Schlumberger does business. An Area is composed of several GeoMarkets.
      country:
        type: string
        example: Romania
        description: A country is a region that is identified as a distinct entity in political geography.
      companyCode:
        type: string
        example: "1507"
        description: The company code is an organizational unit within financial accounting that represents a legal entity
      invoiceDate:
        type: string
        example: 9/10/2019
        description: Specifies the date on which the invoice was initiated by vendor (external supplier). Diplayed on Vendor invoice document
      invoiceReceiveDate:
        type: string
        example: 9/10/2019
        description: Specifies the date on which the invoice was received.
      invoiceDueDate:
        type: string
        format: date
        example: 9/12/2019
        description: Specifies the due date for payment of the retention (when the payment must reach the receiver).
      productLine:
        type: string
        example: MSP
        description: 'A part of the Schlumberger business dedicated to developing and marketing a certain set of technologies that are delivered to our clients by the GeoMarkets. Related Product Lines are combined into a group. '
      paymentDate:
        type: string
        format: date
        example: 9/16/2019
        description: 'Probable Payment Date '
      paidAmount:
        type: number
        format: double
        example: 115000.0
        description: Amount for which the payment transfer medium was issued.
      paymentRef:
        type: string
        example: "36621"
        description: The payment reference contains a key for vendor line items. The payment reference you specify is passed on to the relevant financial institute. When you are processing your account statement, you can use the payment reference to determine which items you have paid and then clear them.
      rejectionDate:
        type: string
        format: date
        example: 9/14/2019
        description: Specifies the date on which the invoice was rejected.
      rejectionReason:
        type: string
        example: RtV - As advised by SLB Point of Contact
        description: Reason for rejecting a particular invoice document.
      pendingReason:
        type: string
        example: Manual Check Needed for Indexing Lines (PO)
        description: Reason for  particular invoice document being in status of pending for further checks and actions.
      currentOwnerAliasOrGIN:
        type: string
        example: "00408450"
        description: GIN number/Alias of Current agent or owner who has current document processing workflow
      currentOwnerFullName:
        type: string
        example: 'Patricia Pacheco '
        description: Name of Current agent or owner who has current document processing workflow

