swagger: '2.0'
info:
  version: 1.0.0
  title:  Operational Activities
  description: The API allows users to query the Job operation attributes available for a specific JobID or based on parameters:- Job Active From-To, Job Status, Prodictline, CountryISOCode, DistrictID. The data classification is private.
  contact:
    name: Intouch Support
    url: 'http://www.intouchsupport.com/index.cfm?event=content.submit&contenttype=5'
  license:
    name: (c) Copyright Schlumberger, unpublished work, created 11/19/2019
externalDocs:
  description: "More information is available here."
  url: "https://link-to-external-documentation"
tags:
  - name: "JobsList"
    description: "API provides list of iDistrict jobs & FDP Operational Activities along with respective header attributes."
  - name: "JobInfo"
    description: "API provides job header attributes for specified job ID."
schemes:
  - https
security:
        - ApiKeyHeader: []
host: "fdp.slb.com"
basePath: '/market-to-cash'
securityDefinitions:
  ApiKeyHeader:
    type: apiKey
    in: header
    name: x-apikey
paths:
  /jobs:
    get:
      summary: Return a list of Jobs along with the respective header attributes.
      operationId: listJobs
      consumes:
        - "application/json"
      produces:
        - "application/json"
      description: Get a list of Jobs/Operational Activities with respective header attribute.
      tags:
        - JobsList
      parameters:
        - name: jobActiveFrom
          in: query
          description: Jobs/Operational Activities active from date (Inclusive)  in RFC3339 full-date format represented in UTC. Example="2019-01-01"
          required: true
          type: string
          format: date
        - name: jobActiveTo
          in: query
          description: Jobs/Operational Activities active to date (Inclusive)  in RFC3339 full-date format represented in UTC. Example="2019-01-01"
          required: true
          type: string
          format: date
        - name: jobStatus
          in: query
          description: Status of the Jobs/Operational Activities being retrieved.
          required: true
          type: string
          enum: [Opportunity, Sold, Unconfirmed, Confirmed, Cancelled, CancelledNonSLB, Completed, Planned, InProgress, StandBy, OperationallyComplete, Forecast P90]
        - name: productLine
          in: query
          description: Productline of Jobs/Operational Activities being retrieved. 
          required: false
          type: string
          enum: [WS, WL, TST, DNM, ALS, CPS, WG, BDT, MI]
        - name: isoCountryCode
          in: query
          description: The two digit ISO country code. Example=US
          required: false
          type: string  
        - name: districtId
          in: query
          description: District ID of Jobs/Operational Activities being retrieved. 
          required: false
          type: string
      responses:
        200:
          description: "200 response - OK"
          schema: 
            $ref: '#/definitions/JobHeaderList'
        400:
          description: "The mandatory parameter is missing."
          schema: 
            $ref: '#/definitions/Error'
        401:
          description: "The endpoint cannot be reached because the request is not authorized."
          schema: 
            $ref: '#/definitions/Error'
        403:
          description: "The request's authorizations don't match the required ones needed to access the resource. Permissions denied."
          schema: 
            $ref: '#/definitions/Error'
        404:
          description: "Incorrect uri specified to consume service."
          schema: 
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema: 
            $ref: '#/definitions/Error'
  /jobs/{jobId}:
    get:
      summary: Returns jobs header attributes information for specified job ID.
      operationId: getJobInfo
      consumes:
        - "application/json"
      produces:
        - "application/json"
      description: Get job ID specific header attributes.
      tags:
        - JobInfo
      parameters:
        - name: jobId
          in: path
          description: Unique identifier of a Job. 
          required: true
          type: string
      responses:
        200:
          description: "200 response - OK"
          schema: 
            $ref: '#/definitions/JobHeader'
        400:
          description: "The mandatory parameter is missing."
          schema: 
            $ref: '#/definitions/Error'
        401:
          description: "The endpoint cannot be reached because the request is not authorized."
          schema: 
            $ref: '#/definitions/Error'
        403:
          description: "The request's authorizations don't match the required ones needed to access the resource. Permissions denied."
          schema: 
            $ref: '#/definitions/Error'
        404:
          description: "Incorrect uri specified to consume service."
          schema: 
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema: 
            $ref: '#/definitions/Error'

definitions:
  JobHeaderList:
    type: object
    required:
        - JobHeader
    properties:
      JobHeader:
        type: object
        items:
          $ref: '#/definitions/JobHeader'
  JobHeader:
    type: object
    properties:
      operationalactivityid:
        type: string
        description: "Relevant only to FDP. Unique identifier for a Operational Activity that is defined in FDP"
        example: A.100000.01.01
      jobid:
        type: string
        description: "Job ID, a unique Job identifier specific to the source systems (iDIstrict, FDP, JMP)"
        example: 2796906, J.100000.01, 30860
      description:
        type: string
        description: "Operational Activity description as captured during the creation of Operational Activity. Applies to FDP only"
        example: azid_8.5in Logging
      startdate:
        type: string
        format: date
        description: "Jobs/Operational Activities start date (UTC) (Inclusive) in RFC3339 full-date format represented in UTC."
        example: 2019-09-01
      enddate:
        type: string
        description: "Jobs/Operational Activities end date (UTC) (Inclusive) in RFC3339 full-date format represented in UTC."
        example: 2019-09-01
      jobgroup:
        type: string
        description: "Comcat job group"
        example: WLES
      jobtype:
        type: string
        description: "Comcat Job Type"
        example: ES-OH-NO
      extjobtypeid:
        type: integer
        description: "Comcat job type Id"
        example: 1037
      bookingstatus:
        type: string
        description: "Booking Status of a Jobs/Operational Activities"
        example: Confirmed
      createddate:
        type: string
        format: date-time
        description: "Job/Operational Activity created date (UTC) in RFC3339 full-date format represented in UTC."
        example: 2019-07-09T23:00:00Z
      createdby:
        type: string
        description: "Alias of LDAP user who created the job"
        example: JohnP
      lastmodifieddate:
        type: string
        format: date-time
        description: "Job/Operational Activity modified date (UTC) in RFC3339 full-date format represented in UTC."
        example: 2019-07-09T23:00:00Z
      lastmodifiedby:
        type: string
        description: "Alias of LDAP user who modified the job"
        example: JohnP
      districtid:
        type: string
        description: "Unique ID provided to a district."
        example: 529, WL-BRGN
      districtname:
        type: string
        description: "Name of the district"
        example: WL BERGEN
      districttimezonedisplayname:
        type: string
        description: "District timezone display name"
        example: West Asia Standard Time
      districttimezonestandardname:
        type: string
        description: "District timezone name"
        example: West Asia Standard Time
      customerid:
        type: string
        description: "Customer Id (Seibel Id)"
        example: 1-19VYR5, 1+28B+6
      customersapittid:
        type: integer
        description: "SAPITTID of Customer"
        example: 30012156
      customername:
        type: string
        description: "Name of customer"
        example: TURKMENGAS STATE CONCERN
      customerRigcountry:
        type: string
        description: "Country of customer where the rig belongs to"
        example: NORWAY
      customerBillTocountry:
        type: string
        description: "Country of customer billed to"
        example: NORWAY
      customeragreementname:
        type: string
        description: "Siebel ID for Customer Agreement"
        example: 1-2378619137
      geomarketname:
        type: string
        description: "Name of Geomarket"
        example: RCA
      subgeomarketname:
        type: string
        description: "Name of Sub-Geomarket"
        example: TKG
      productline:
        type: string
        description: "Product line"
        example: WL
      projectid:
        type: string
        description: "Project Id under which the Operation is defined. Relevant only to FDP"
        example: P.6000153
      operationid:
        type: string
        description: "Operation Id under which this Operational Activity is defined in FDP."
        example: O.6000153.01
      opstartdate:
        type: string
        format: date-time
        description: "Rig/Operation up/start date (UTC)"
        example: 2019-09-01T00:00:17.59
      openddate:
        type: string
        format: date-time
        description: "Rig/Operation down/end date (UTC)"
        example: 2019-09-01T00:00:17.59
      operationstatus:
        type: string
        description: "Operational status of the Operational Activity. Relevant to FDP only."
        example: Complete
      remoteopsrequired:
        type: boolean 
        description: "Whether the Job/Operational Activity involves Remote operation"
        example: true
      remoteopslocation:
        type: string
        description: "Remote operation location of Job/Operational Activity in case where Remote Ops is enabled"
        example: ROC-USA-MID
      Wells:
        type: array
        description: list of well/s for this operational activity.
        items:
          $ref: '#/definitions/Well'
      rignumber:
        type: number
        description: "Rig number"
        example: 63006656
      extrigid:
        type: string
        description: "CRM rig ID"
        example: 1-1B1M43V
      rigname:
        type: string
        description: "Name of the Rig"
        example: Patterson
      rigtype:
        type: string
        description: "Type of Rig"
        enum: [LAND RIG, JACKUP, SEMI-SUBMERSIBLE, TENDER ASSISTED, Barges, Drillship, Fixed Platform, Floating Platform, HYBRID, INLAND BARGE, MAST, SLANT RIG, TLP, Coiled Tubing Unit, Intervention Vessel, Unaccessible to SLB, New Build, Cementing Fleet, Stimulation Vessel]
      rigenvironment:
        type: string
        description: "Rig operating environment"
        enum: [Offshore - Deepwater, Offshore - Shallow, Land, Swamp/Inland Waters, Rig Less,Rig Unknown]
      probablity:
        type: number
        description: "Probability of job execution"
        example: 100
      padname:
        type: string
        description: "Pad name"
        example: Masters Unit 2AH 3AH 6SH 7SH
      padwellmaster:
        type: number
        description: "Pad master number"
        example: 0065893632
      ipmprojectnumber:
        type: string
        description: "IPM Project Number "
        example: R.00000102.01.01.01
      saphrsegmentcode:
        type: string
        description: "SAP HR segment code"
        example: ALS
      sapprojectnumber:
        type: string
        description: "SAP Project Number of job"
        example: J.19.031187
      riskprofilevalue:
        type: integer
        description: "Risk profile value"
        example: 0
      serviceinstructions:
        type: string
        description: "Service summary of job (specific to WireLine)"
        example: SLK mechanical services
      unitsystem:
        type: string
        description: "UOM System set for this Job/Operational Activity"
        example: Metric
      pppid:
        type: number
        description: "PPP ID"
        example: 118832
      guid:
        type: string
        description: "Global Unique Identifier"
        example: 709231D1-5901-4E6E-81F5-70425D946B16
      paginationmetadata:
        type: object
        uniqueItems: true
        items:
          $ref: '#/definitions/paginationmetadata'
      links:
        type: object
        uniqueItems: true
        items:
          $ref: '#/definitions/links'
  Well:
    type: object
    properties:
      wellid: 
        type: string
        description: "Well ID (Siebel Id)"
        example: 1-1KS1SO9
      wellmasternumber:
        type: number
        description: "Well master number"
        example: 630156369
      wellname:
        type: string
        description: "Name of well"
        example: OCS-P0240 HENRY 7B
      wellfield:
        type: string
        description: "Well field"
        example: Ninian
      wellenvironment:
        type: string
        description: "Well environment"
        example: Offshore - Shallow
      welltype:
        type: string
        description: "Type of well"
        example: Development
      wellsapittid:
        type: number
        description: "SAP ITT ID of Well"
        example: 65899148
      wellapiuwi:
        type: string
        description: "API-UWI  of Well"
        example: 50-029-21031-01-00
  Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          example: 1001
        message:
          type: string
          example: Unexpected error occured. Please try again.
  links:
    required:
      - pageOf
    properties:
      pageOf:
        type: string
        format: uri
        description: Link to the collection
      next:
        type: string
        format: uri
        description: Link to the next page in the paginated collection
      previous:
        type: string
        format: uri
        description: Link to the previous page in the paginated collection
  paginationmetadata:
    required:
      - pageSize
      - currentPage
      - totalPages
      - totalCount
    properties:
      pageSize:
        type: integer
        description: Count of items per page
      currentPage:
        type: integer
        description: Current page number
      totalPages:
        type: integer
        description: Total number of pages
      totalCount:
        type: number
        description: Count of total records
